// ReverseModule.idl
module ReverseModule {
 interface Reverse {
 string reverse_string(in string str);
 };
};

1) idlj -fall ReverseModule.idl
2) javac -d . ReverseModule/*.java *.java
3) orbd -ORBInitialPort 1050
4) java ReverseServer -ORBInitialPort 1050 -ORBInitialHost localhost
5) java ReverseClient -ORBInitialPort 1050 -ORBInitialHost localhost